apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.environment }}-ingress
  labels:
    app: {{ .Values.environment }}
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.environment }}-service
            port:
              number: 80
