apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.environment }}
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.global.environment}}
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: app-chart
      repoURL: "{{ .Values.global.chart.repo }}"
      targetRevision: "{{ .Values.global.chart.targetRevision }}"
      helm:
        valueFiles: 
          - $values/environments/{{ .Values.global.environment}}/values.yaml
    - repoURL: "{{ .Values.global.values.repo }}"
      targetRevision: "{{ .Values.global.values.targetRevision }}"
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true