name: Node.js CI
on:
  push:
    branches:
      - 'change-replicas-dev'


jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test_var: ${{ env.test-var }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Install dependencies
      - name: Install dependencies
        run: echo "test-var=julian">> $GITHUB_ENV

  kuku-pupu:
    #needs: test
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Install dependencies
      - name: Install dependencies
        run: echo "Received value ${{ needs.test.outputs.test_var }}"
