name: Node.js CI

on:
  push:
    branches:
      - main
      - change-replicas-dev


jobs:
  test:
    runs-on: ubuntu-latest
    
    
  

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Install dependencies
      - name: Install dependencies
        run: echo ${{ github.ref_name }}
      
