name: Node.js CI
on:
  push:
    branches:
      - 'change-replicas-dev'


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        classmates: [nadav, regev, marco]
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Install dependencies
      - name: Install dependencies
        run: echo ${{ matrix.classmates }}


